apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
spec:
  selector:
    matchLabels:
      app: account-pod
  template:
    metadata:
      labels:
        app: account-pod
    spec:
      containers:
      - name: account-container
        image: benhassan98/account-service-image
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: account-pod
  ports:
  - name: account-service-port
    protocol: TCP
    port: 8080
    targetPort: 8080
                                                                                                                                    
